<!DOCTYPE html>
<html>
	<head>
		<meta charset=utf-8>
		<title>Что читают</title>
		<style>
			table {
    			border-collapse: collapse;
    			width: 100%;
			}
  			h1 {
    			margin: 2em 0; 
  			}
			td{ 
   				text-align: center; 
   				border: 1px solid #ddd; 
   				padding:.5em 5px;
    			font-size: 1.2em;
			}
  		</style>
	</head>
	<body>
		<h1>Что читают</h1>
		<?if (isset($result)):?>
			<table>
				<?foreach($result as $item):?>
					<tr>
						<td><a href="<?=$item['url']?>"><?=$item['title']?></a></td>
						<td><?=$item['clicks']?></td>	
					<tr>	
				<?endforeach?>
			<table>	
		<?endif?>
	</body>	
</html>		